//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIPedro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class asignaturas
    {
        public asignaturas()
        {
            this.calificaciones = new HashSet<calificaciones>();
        }
    
        public string CodiAsig { get; set; }
        public int Grupo { get; set; }
        public string NombAsig { get; set; }
        public Nullable<int> Creditos { get; set; }
        public string DiaAsig { get; set; }
        public string HoraAsig { get; set; }
        public string LugarAsig { get; set; }
        public string Profesores_CeduProf { get; set; }
    
        public virtual ICollection<calificaciones> calificaciones { get; set; }
        public virtual profesores profesores { get; set; }
    }
}
