//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIPedro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class calificaciones
    {
        public string Asignaturas_CodiAsig { get; set; }
        public int Asignaturas_Grupo { get; set; }
        public string Estudiantes_CeduEstu { get; set; }
        public Nullable<float> Nota1 { get; set; }
        public Nullable<float> Nota2 { get; set; }
        public Nullable<float> Nota3 { get; set; }
        public Nullable<float> Habilitacion { get; set; }
    
        public virtual asignaturas asignaturas { get; set; }
        public virtual estudiantes estudiantes { get; set; }
    }
}
