//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIPedro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class login
    {
        public login()
        {
            this.estudiantes = new HashSet<estudiantes>();
            this.profesores = new HashSet<profesores>();
        }
    
        public string Usuario { get; set; }
        public string Password { get; set; }
    
        public virtual ICollection<estudiantes> estudiantes { get; set; }
        public virtual ICollection<profesores> profesores { get; set; }
    }
}
